In [1]:
import yfinance as yf

In [2]:
# 마이크로소프트 주식 정보 가져오는 객체 생성(Ticker)
msft = yf.Ticker("MSFT")
# 회사 정보
display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1790812800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 525.18,
 'open': 531.68,
 'dayLow': 528.82,
 'dayHigh': 535.69,
 'regularMarketPreviousClose': 525.18,
 'regularMarketOpen': 531.68,
 'regularMarketDayLow': 528.82,
 'regularMarketDayHigh': 535.69,
 'dividendRate': 3.92,
 'dividendYield': 0.75,
 'exDividendDate': 1795046400,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.78,
 'beta': 1.099,
 'trailingPE': 29.487463,
 'forwardPE': 22.354725,
 'volume': 21098949,
 'regularMarketVolume': 21098949,
 'averageVolume': 28126893,
 'averageVolume10days': 22827110,
 'averageDailyVolume10Day': 22827110,
 'bid': 529.2,
 'ask': 531.97,
 'bidSize': 9,
 'askSize': 4,
 'marketCap': 3930341244928,
 'nonDilutedMarketCap': 3717153817339,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'fulldayPrice': 529.3,
 'fulldayChange': 4.5341187,
 'fulldayChangePercent': 0.8633457,
 'priceToSalesTrailing12Months': 11.84412,
 'fiftyDayAverage': 490.5938,
 'twoHundredDayAverage': 433.0749,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.006930957,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3983796338688,
 'profitMargins': 0.40305,
 'floatShares': 7414555684,
 'sharesOutstanding': 7425545491,
 'sharesShort': 67346414,
 'sharesShortPriorMonth': 68544953,
 'sharesShortPreviousMonthDate': 1786665600,
 'dateShortInterest': 1789430400,
 'sharesPercentSharesOut': 0.0091,
 'heldPercentInsiders': 0.00090000004,
 'heldPercentInstitutions': 0.75778997,
 'shortRatio': 3.21,
 'shortPercentOfFloat': 0.0091,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.886091,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.95,
 'forwardEps': 23.67732,
 'pegRatio': 1.71,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 12.005,
 'enterpriseToEbitda': 20.51,
 '52WeekChange': 0.0022901297,
 'SandP52WeekChange': 0.15776992,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1787184000,
 'quoteType': 'EQUITY',
 'currentPrice': 529.3,
 'targetHighPrice': 870.0,
 'targetLowPrice': 440.0,
 'targetMeanPrice': 585.6149,
 'targetMedianPrice': 585.0,
 'recommendationMean': 1.28571,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'postMarketTime': 1791331105,
 'regularMarketTime': 1791316801,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'marketState': 'POSTPOST',
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 17.95,
 'epsForward': 23.67732,
 'epsCurrentYear': 19.76867,
 'priceEpsCurrentYear': 26.77469,
 'fiftyDayAverageChange': 38.706177,
 'fiftyDayAverageChangePercent': 0.07889659,
 'twoHundredDayAverageChange': 96.2251,
 'twoHundredDayAverageChangePercent': 0.22219044,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': 0.07823985,
 'postMarketPrice': 529.7141,
 'postMarketChange': 0.41412354,
 'regularMarketChange': 4.12,
 'regularMarketChangePercent': 0.784492,
 'regularMarketPrice': 529.3,
 'regularMarketDayRange': '528.82 - 535.69',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 28126893,
 'fiftyTwoWeekLowChange': 180.09998,
 'fiftyTwoWeekLowChangePercent': 0.51575017,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -24.419983,
 'fiftyTwoWeekHighChangePercent': -0.044101685,
 'fiftyTwoWeekChangePercent': 0.22901297,
 'dividendDate': 1796860800,
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6173}

In [3]:
# 최근 주가 정보 확인 
# 최근 5일 간의 주가 데이터 가져오기
hist = msft.history(period="5d")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-09-30 00:00:00-04:00,511.609985,519.830017,510.309998,512.900024,27223300,0.0,0.0
2026-10-01 00:00:00-04:00,519.880005,522.849976,512.169983,512.799988,19731900,0.0,0.0
2026-10-02 00:00:00-04:00,519.390015,522.500000,513.659973,517.530029,17822300,0.0,0.0
2026-10-05 00:00:00-04:00,521.619995,532.349976,521.469971,525.179993,26604800,0.0,0.0
2026-10-06 00:00:00-04:00,531.679993,535.690002,528.780029,529.299988,21092600,0.0,0.0

In [4]:
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         14   41     1     0           0
1    -1m         14   39     2     0           0
2    -2m         14   38     3     0           0
3    -3m         14   40     3     0           0